-- List shows by their rating sum
SELECT TV_SHOWS.TITLE, SUM(TV_SHOW_RATINGS.RATING) AS RATING_SUM
FROM TV_SHOWS
JOIN TV_SHOW_RATINGS ON TV_SHOWS.ID = TV_SHOW_RATINGS.SHOW_ID
GROUP BY TV_SHOWS.ID, TV_SHOWS.TITLE
ORDER BY RATING_SUM DESC;
